name: ML Security CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: |
          cd backend
          npm install

      # Syntax check
      - name: Syntax Check
        run: |
          cd backend
          node -c server.js

      # Docker login
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t rithikka123/ml-security:latest .
          docker push rithikka123/ml-security:latest

      # Success
      - name: Done
        run: echo "CI/CD SUCCESS 🚀"