name: ML Security CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: |
          cd backend
          npm install

      # Syntax check
      - name: Syntax Check
        run: |
          cd backend
          node -c server.js

      # Docker login (MOST STABLE METHOD)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build image (IMPORTANT FIX: backend context)
      - name: Build Docker Image
        run: |
          docker build -t rithikka123/ml-security:latest backend

      # Push image
      - name: Push Docker Image
        run: |
          docker push rithikka123/ml-security:latest

      # Done
      - name: Success
        run: echo "CI/CD SUCCESS 🚀"