name: ML Security CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v5

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      # Install dependencies
      - name: Install Dependencies
        run: |
          cd backend
          npm install

      # Check server file
      - name: Syntax Check
        run: |
          cd backend
          node -c server.js

      # Docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t rithikka123/ml-security:latest .

      # Push image
      - name: Push Docker Image
        run: |
          docker push rithikka123/ml-security:latest

      # Success
      - name: Done
        run: echo "CI/CD SUCCESS 🚀"